---
- name: install the golang
  get_url: >
    url={{ golang_url }}
    dest=/usr/local/src
- name: untar the golang
  unarchive: >
    src=/usr/local/src/{{ tar_name }}
    dest=/usr/local/
    copy=no
- name: copy golang.sh
  copy: src=golang.sh dest=/etc/profile.d/

- name: source golang.sh
  shell: /bin/bash -lc "source /etc/profile.d/golang.sh"
  failed_when: False
